apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
  labels:
    app: devops-project
  namespace: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project
        image: nithin8/devops-project  
        ports:
        - containerPort: 3000
